apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: caasperlis
  namespace: infra-argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/adfinis/argocd-configs
        revision: feat/appsets
        directories:
          - path: "manifests/dev/caasperlis/*"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: caasperlis
      sources:
        - repoURL: https://charts.adfinis.com
          targetRevision: 0.10.4
          chart: "caasperli"
          helm:
            releaseName: "caasperli-{{path.basename}}"
            valueFiles:
              - "$values/manifests/dev/caasperlis/general.yaml"
              - "$values/{{path}}/values.yaml"
        - repoURL: https://github.com/adfinis/argocd-configs
          targetRevision: feat/appsets
          ref: values
      destination:
        server: "https://kubernetes.default.svc"
        namespace: caasperlis
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
